server:
  port: 8000
spring:
  application:
    name: customer-service
  threads:
    virtual:
      enabled: true
  # Postgresql configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
spring-boot:
  version: 3.2.2
